language: elixir
elixir:
  - 1.7
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
services:
  - postgresql
env:
  global:
    - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test