language: elixir
elixir:
  - 1.7
otp_release:
  - 20.2.4
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
addons:
  postgresql: 
    - '9.5'
env:
  global:
    - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix do deps.get, mix test